# Keep Zephyr tickrate consistent with embassy tickrate
CONFIG_SYS_CLOCK_TICKS_PER_SEC=10000

# Logging
CONFIG_LOG=y
CONFIG_LOG_USE_VLA=y

# Fuel Gauge
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_SENSOR_INIT_PRIORITY=90
CONFIG_FUEL_GAUGE=y
CONFIG_SBS_GAUGE_NEW_API=y
CONFIG_EMUL=y
CONFIG_EMUL_SBS_GAUGE=y